CREATE TABLE symptom_questionnaires (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stable_key      VARCHAR2(120) NOT NULL UNIQUE,
    display_name    VARCHAR2(200) NOT NULL,
    active          BOOLEAN DEFAULT TRUE NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_symptom_questionnaires_stable_key CHECK (length(trim(stable_key)) > 0),
    CONSTRAINT chk_symptom_questionnaires_display_name CHECK (length(trim(display_name)) > 0)
);

CREATE TABLE symptom_questionnaire_versions (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    questionnaire_id    NUMBER(19) NOT NULL REFERENCES symptom_questionnaires(id) ON DELETE CASCADE,
    version_number      NUMBER(10) NOT NULL,
    status              VARCHAR2(40) NOT NULL,
    scoring_method      VARCHAR2(40) NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    published_at        TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ux_symptom_questionnaire_versions_number UNIQUE (questionnaire_id, version_number),
    CONSTRAINT chk_symptom_questionnaire_versions_number CHECK (version_number > 0),
    CONSTRAINT chk_symptom_questionnaire_versions_status CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    CONSTRAINT chk_symptom_questionnaire_versions_scoring CHECK (scoring_method IN ('SUM'))
);

CREATE TABLE symptom_questions (
    id                          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    questionnaire_version_id    NUMBER(19) NOT NULL REFERENCES symptom_questionnaire_versions(id) ON DELETE CASCADE,
    stable_key                  VARCHAR2(120) NOT NULL,
    label                       VARCHAR2(500) NOT NULL,
    help_text                   VARCHAR2(1000),
    answer_type                 VARCHAR2(40) NOT NULL,
    required                    BOOLEAN DEFAULT TRUE NOT NULL,
    sort_order                  NUMBER(10) DEFAULT 0 NOT NULL,
    score_weight                NUMBER(8,2) DEFAULT 1.00 NOT NULL,
    min_numeric_value           NUMBER(8,2),
    max_numeric_value           NUMBER(8,2),
    CONSTRAINT ux_symptom_questions_version_key UNIQUE (questionnaire_version_id, stable_key),
    CONSTRAINT ux_symptom_questions_id_version UNIQUE (id, questionnaire_version_id),
    CONSTRAINT chk_symptom_questions_key CHECK (length(trim(stable_key)) > 0),
    CONSTRAINT chk_symptom_questions_label CHECK (length(trim(label)) > 0),
    CONSTRAINT chk_symptom_questions_type CHECK (answer_type IN ('SINGLE_CHOICE', 'NUMERIC', 'TEXT')),
    CONSTRAINT chk_symptom_questions_sort_order CHECK (sort_order >= 0),
    CONSTRAINT chk_symptom_questions_weight CHECK (score_weight >= 0),
    CONSTRAINT chk_symptom_questions_numeric_range CHECK (
        min_numeric_value IS NULL
        OR max_numeric_value IS NULL
        OR min_numeric_value <= max_numeric_value
    )
);

CREATE TABLE symptom_question_options (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id     NUMBER(19) NOT NULL REFERENCES symptom_questions(id) ON DELETE CASCADE,
    stable_key      VARCHAR2(120) NOT NULL,
    label           VARCHAR2(300) NOT NULL,
    numeric_score   NUMBER(8,2) DEFAULT 0.00 NOT NULL,
    sort_order      NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT ux_symptom_question_options_question_key UNIQUE (question_id, stable_key),
    CONSTRAINT ux_symptom_question_options_id_question UNIQUE (id, question_id),
    CONSTRAINT chk_symptom_question_options_key CHECK (length(trim(stable_key)) > 0),
    CONSTRAINT chk_symptom_question_options_label CHECK (length(trim(label)) > 0),
    CONSTRAINT chk_symptom_question_options_sort_order CHECK (sort_order >= 0)
);

CREATE TABLE symptom_check_ins (
    id                          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_profile_id          NUMBER(19) NOT NULL REFERENCES patient_profiles(id) ON DELETE CASCADE,
    questionnaire_version_id    NUMBER(19) NOT NULL REFERENCES symptom_questionnaire_versions(id),
    check_in_date               DATE NOT NULL,
    flare_state                 VARCHAR2(40) NOT NULL,
    notes                       VARCHAR2(1000),
    total_symptom_score         NUMBER(8,2) DEFAULT 0.00 NOT NULL,
    created_at                  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at                  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT ux_symptom_check_ins_id_version UNIQUE (id, questionnaire_version_id),
    CONSTRAINT ux_symptom_check_ins_patient_date UNIQUE (patient_profile_id, check_in_date),
    CONSTRAINT chk_symptom_check_ins_flare
        CHECK (flare_state IN ('NO_FLARE', 'SUSPECTED_FLARE', 'ACTIVE_FLARE')),
    CONSTRAINT chk_symptom_check_ins_score CHECK (total_symptom_score >= 0),
    CONSTRAINT chk_symptom_check_ins_notes CHECK (notes IS NULL OR length(trim(notes)) > 0)
);

CREATE TABLE symptom_check_in_answers (
    id                          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_in_id                 NUMBER(19) NOT NULL REFERENCES symptom_check_ins(id) ON DELETE CASCADE,
    questionnaire_version_id    NUMBER(19) NOT NULL,
    question_id                 NUMBER(19) NOT NULL REFERENCES symptom_questions(id),
    option_id                   NUMBER(19) REFERENCES symptom_question_options(id),
    answer_text                 VARCHAR2(1000),
    answer_numeric              NUMBER(8,2),
    numeric_score               NUMBER(8,2) DEFAULT 0.00 NOT NULL,
    CONSTRAINT ux_symptom_check_in_answers_check_question UNIQUE (check_in_id, question_id),
    CONSTRAINT fk_symptom_check_in_answers_check_version
        FOREIGN KEY (check_in_id, questionnaire_version_id)
        REFERENCES symptom_check_ins(id, questionnaire_version_id),
    CONSTRAINT fk_symptom_check_in_answers_question_version
        FOREIGN KEY (question_id, questionnaire_version_id)
        REFERENCES symptom_questions(id, questionnaire_version_id),
    CONSTRAINT fk_symptom_check_in_answers_option_question
        FOREIGN KEY (option_id, question_id)
        REFERENCES symptom_question_options(id, question_id),
    CONSTRAINT chk_symptom_check_in_answers_text
        CHECK (answer_text IS NULL OR length(trim(answer_text)) > 0),
    CONSTRAINT chk_symptom_check_in_answers_score CHECK (numeric_score >= 0),
    CONSTRAINT chk_symptom_check_in_answers_one_value CHECK (
        option_id IS NOT NULL
        OR answer_text IS NOT NULL
        OR answer_numeric IS NOT NULL
    )
);

CREATE INDEX ix_symptom_questionnaire_versions_active
    ON symptom_questionnaire_versions(questionnaire_id, status);
CREATE UNIQUE INDEX ux_symptom_questionnaire_versions_one_active
    ON symptom_questionnaire_versions (
        CASE WHEN status = 'ACTIVE' THEN questionnaire_id END
    );
CREATE INDEX ix_symptom_questions_version_order
    ON symptom_questions(questionnaire_version_id, sort_order, id);
CREATE INDEX ix_symptom_question_options_question_order
    ON symptom_question_options(question_id, sort_order, id);
CREATE INDEX ix_symptom_check_ins_patient_date
    ON symptom_check_ins(patient_profile_id, check_in_date DESC);

INSERT INTO symptom_questionnaires (stable_key, display_name, active)
VALUES ('ibd-symptom-check-in', 'IBD symptom check-in', TRUE);

INSERT INTO symptom_questionnaire_versions (
    questionnaire_id, version_number, status, scoring_method, published_at)
SELECT id, 1, 'ACTIVE', 'SUM', CURRENT_TIMESTAMP
FROM symptom_questionnaires
WHERE stable_key = 'ibd-symptom-check-in';

INSERT INTO symptom_questions (
    questionnaire_version_id, stable_key, label, help_text, answer_type, required, sort_order,
    score_weight, min_numeric_value, max_numeric_value
)
SELECT questionnaire_version.id, question_seed.stable_key, question_seed.label,
       question_seed.help_text, question_seed.answer_type, TRUE, question_seed.sort_order,
       1.00, question_seed.min_numeric_value, question_seed.max_numeric_value
FROM symptom_questionnaire_versions questionnaire_version
JOIN symptom_questionnaires questionnaire
    ON questionnaire.id = questionnaire_version.questionnaire_id
CROSS JOIN (
    SELECT 'stool-frequency' stable_key, 'Stool frequency' label,
           'Number of stools in the last 24 hours' help_text, 'NUMERIC' answer_type,
           10 sort_order, CAST(0.00 AS NUMBER(8,2)) min_numeric_value,
           CAST(30.00 AS NUMBER(8,2)) max_numeric_value FROM dual
    UNION ALL
    SELECT 'abdominal-pain', 'Abdominal pain', 'Pain severity in the last 24 hours',
           'SINGLE_CHOICE', 20, NULL, NULL FROM dual
    UNION ALL
    SELECT 'blood-in-stool', 'Blood in stool', 'Blood observed in stool',
           'SINGLE_CHOICE', 30, NULL, NULL FROM dual
    UNION ALL
    SELECT 'urgency', 'Urgency', 'Urgency severity in the last 24 hours',
           'SINGLE_CHOICE', 40, NULL, NULL FROM dual
    UNION ALL
    SELECT 'general-wellbeing', 'General wellbeing', 'Overall wellbeing today',
           'SINGLE_CHOICE', 50, NULL, NULL FROM dual
) question_seed
WHERE questionnaire.stable_key = 'ibd-symptom-check-in'
  AND questionnaire_version.version_number = 1;

INSERT INTO symptom_question_options (question_id, stable_key, label, numeric_score, sort_order)
SELECT question.id, option_seed.stable_key, option_seed.label,
       option_seed.numeric_score, option_seed.sort_order
FROM symptom_questions question
JOIN symptom_questionnaire_versions questionnaire_version
    ON questionnaire_version.id = question.questionnaire_version_id
JOIN symptom_questionnaires questionnaire
    ON questionnaire.id = questionnaire_version.questionnaire_id
CROSS JOIN (
    SELECT 'none' stable_key, 'None' label, CAST(0.00 AS NUMBER(8,2)) numeric_score,
           10 sort_order FROM dual
    UNION ALL SELECT 'mild', 'Mild', 1.00, 20 FROM dual
    UNION ALL SELECT 'moderate', 'Moderate', 2.00, 30 FROM dual
    UNION ALL SELECT 'severe', 'Severe', 3.00, 40 FROM dual
) option_seed
WHERE questionnaire.stable_key = 'ibd-symptom-check-in'
  AND question.stable_key IN ('abdominal-pain', 'urgency');

INSERT INTO symptom_question_options (question_id, stable_key, label, numeric_score, sort_order)
SELECT question.id, option_seed.stable_key, option_seed.label,
       option_seed.numeric_score, option_seed.sort_order
FROM symptom_questions question
JOIN symptom_questionnaire_versions questionnaire_version
    ON questionnaire_version.id = question.questionnaire_version_id
JOIN symptom_questionnaires questionnaire
    ON questionnaire.id = questionnaire_version.questionnaire_id
CROSS JOIN (
    SELECT 'none' stable_key, 'None' label, CAST(0.00 AS NUMBER(8,2)) numeric_score,
           10 sort_order FROM dual
    UNION ALL SELECT 'trace', 'Trace', 1.00, 20 FROM dual
    UNION ALL SELECT 'visible', 'Visible', 2.00, 30 FROM dual
    UNION ALL SELECT 'significant', 'Significant', 3.00, 40 FROM dual
) option_seed
WHERE questionnaire.stable_key = 'ibd-symptom-check-in'
  AND question.stable_key = 'blood-in-stool';

INSERT INTO symptom_question_options (question_id, stable_key, label, numeric_score, sort_order)
SELECT question.id, option_seed.stable_key, option_seed.label,
       option_seed.numeric_score, option_seed.sort_order
FROM symptom_questions question
JOIN symptom_questionnaire_versions questionnaire_version
    ON questionnaire_version.id = question.questionnaire_version_id
JOIN symptom_questionnaires questionnaire
    ON questionnaire.id = questionnaire_version.questionnaire_id
CROSS JOIN (
    SELECT 'well' stable_key, 'Well' label, CAST(0.00 AS NUMBER(8,2)) numeric_score,
           10 sort_order FROM dual
    UNION ALL SELECT 'slightly-unwell', 'Slightly unwell', 1.00, 20 FROM dual
    UNION ALL SELECT 'unwell', 'Unwell', 2.00, 30 FROM dual
    UNION ALL SELECT 'very-unwell', 'Very unwell', 3.00, 40 FROM dual
) option_seed
WHERE questionnaire.stable_key = 'ibd-symptom-check-in'
  AND question.stable_key = 'general-wellbeing';
