CREATE TABLE patient_access_tokens (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash VARCHAR2(64) NOT NULL UNIQUE,
    client_type VARCHAR2(40) NOT NULL,
    display_label VARCHAR2(120) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_used_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    revocation_reason VARCHAR2(120)
);

CREATE INDEX idx_patient_access_tokens_user_id
    ON patient_access_tokens(user_id);

CREATE INDEX idx_patient_access_tokens_active_user
    ON patient_access_tokens(user_id, revoked_at, created_at DESC);

CREATE TABLE patient_access_token_scopes (
    token_id NUMBER(19) NOT NULL REFERENCES patient_access_tokens(id) ON DELETE CASCADE,
    scope VARCHAR2(80) NOT NULL,
    PRIMARY KEY (token_id, scope)
);
