ALTER TABLE patient_access_tokens
    ADD resource VARCHAR2(255);

UPDATE patient_access_tokens
SET resource = 'http://localhost:8080/api/mcp'
WHERE resource IS NULL;

ALTER TABLE patient_access_tokens
    MODIFY (resource NOT NULL);

CREATE TABLE oauth_authorization_codes (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash VARCHAR2(64) NOT NULL UNIQUE,
    user_id NUMBER(19) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    client_id VARCHAR2(255) NOT NULL,
    client_display_label VARCHAR2(120) NOT NULL,
    redirect_uri VARCHAR2(500) NOT NULL,
    resource VARCHAR2(255) NOT NULL,
    code_challenge VARCHAR2(128) NOT NULL,
    code_challenge_method VARCHAR2(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_oauth_authorization_codes_user_id
    ON oauth_authorization_codes(user_id);

CREATE INDEX idx_oauth_authorization_codes_expires_at
    ON oauth_authorization_codes(expires_at);

CREATE TABLE oauth_authorization_code_scopes (
    authorization_code_id NUMBER(19) NOT NULL REFERENCES oauth_authorization_codes(id) ON DELETE CASCADE,
    scope VARCHAR2(80) NOT NULL,
    PRIMARY KEY (authorization_code_id, scope)
);
