CREATE TABLE oauth_registered_clients (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id VARCHAR2(80) NOT NULL UNIQUE,
    client_name VARCHAR2(120),
    token_endpoint_auth_method VARCHAR2(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE oauth_registered_client_redirect_uris (
    registered_client_id NUMBER(19) NOT NULL REFERENCES oauth_registered_clients(id) ON DELETE CASCADE,
    redirect_uri_order NUMBER(10) NOT NULL,
    redirect_uri VARCHAR2(500) NOT NULL,
    PRIMARY KEY (registered_client_id, redirect_uri_order)
);

CREATE TABLE oauth_registered_client_scopes (
    registered_client_id NUMBER(19) NOT NULL REFERENCES oauth_registered_clients(id) ON DELETE CASCADE,
    scope VARCHAR2(80) NOT NULL,
    PRIMARY KEY (registered_client_id, scope)
);
