ALTER TABLE oauth_registered_clients
    ADD application_type VARCHAR2(16) DEFAULT 'native' NOT NULL;

CREATE TABLE oauth_registered_client_grant_types (
    registered_client_id NUMBER(19) NOT NULL REFERENCES oauth_registered_clients(id) ON DELETE CASCADE,
    grant_type_order NUMBER(10) NOT NULL,
    grant_type VARCHAR2(32) NOT NULL,
    PRIMARY KEY (registered_client_id, grant_type_order)
);

INSERT INTO oauth_registered_client_grant_types (registered_client_id, grant_type_order, grant_type)
SELECT id, 0, 'authorization_code'
FROM oauth_registered_clients;

ALTER TABLE patient_access_tokens
    ADD refresh_family_id VARCHAR2(64);

CREATE TABLE oauth_refresh_token_families (
    family_id VARCHAR2(64) PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    revocation_reason VARCHAR2(120)
);

CREATE INDEX idx_patient_access_tokens_refresh_family
    ON patient_access_tokens(refresh_family_id);

CREATE TABLE oauth_refresh_tokens (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR2(64) NOT NULL UNIQUE,
    family_id VARCHAR2(64) NOT NULL REFERENCES oauth_refresh_token_families(family_id),
    user_id NUMBER(19) NOT NULL REFERENCES users(id),
    client_id VARCHAR2(500) NOT NULL,
    client_source VARCHAR2(32) NOT NULL,
    client_type VARCHAR2(40) NOT NULL,
    display_label VARCHAR2(120) NOT NULL,
    "resource" VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    replacement_token_id NUMBER(19) REFERENCES oauth_refresh_tokens(id),
    revoked_at TIMESTAMP WITH TIME ZONE,
    revocation_reason VARCHAR2(120)
);

CREATE INDEX idx_oauth_refresh_tokens_family ON oauth_refresh_tokens(family_id);
CREATE INDEX idx_oauth_refresh_tokens_client ON oauth_refresh_tokens(client_id);

ALTER TABLE patient_access_tokens
    ADD CONSTRAINT fk_patient_access_tokens_refresh_family
    FOREIGN KEY (refresh_family_id) REFERENCES oauth_refresh_token_families(family_id);

CREATE TABLE oauth_refresh_token_scopes (
    refresh_token_id NUMBER(19) NOT NULL REFERENCES oauth_refresh_tokens(id) ON DELETE CASCADE,
    scope VARCHAR2(80) NOT NULL,
    PRIMARY KEY (refresh_token_id, scope)
);
