CREATE TABLE lab_test_definitions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(64) NOT NULL UNIQUE,
    label_key VARCHAR2(120) NOT NULL UNIQUE,
    category VARCHAR2(40) NOT NULL,
    canonical_unit VARCHAR2(40) NOT NULL,
    display_scale NUMBER(5) NOT NULL CHECK (display_scale BETWEEN 0 AND 6),
    active BOOLEAN DEFAULT TRUE NOT NULL,
    sort_order NUMBER(10) NOT NULL
);

CREATE TABLE lab_test_unit_definitions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_definition_id NUMBER(19) NOT NULL REFERENCES lab_test_definitions(id) ON DELETE CASCADE,
    unit_code VARCHAR2(40) NOT NULL,
    conversion_type VARCHAR2(24) NOT NULL,
    multiplier NUMBER(24, 12) NOT NULL CHECK (multiplier > 0),
    sort_order NUMBER(10) NOT NULL,
    UNIQUE (test_definition_id, unit_code)
);

CREATE TABLE lab_result_sets (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_profile_id NUMBER(19) NOT NULL REFERENCES patient_profiles(id),
    collection_date DATE NOT NULL,
    notes VARCHAR2(2000),
    source VARCHAR2(32) NOT NULL,
    confirmation_status VARCHAR2(32) NOT NULL,
    created_by_user_id NUMBER(19) NOT NULL REFERENCES users(id),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    version NUMBER(19) DEFAULT 0 NOT NULL,
    removed_at TIMESTAMP WITH TIME ZONE,
    removed_by_user_id NUMBER(19) REFERENCES users(id),
    removal_reason VARCHAR2(500),
    CONSTRAINT chk_lab_result_set_removal CHECK (
        (removed_at IS NULL AND removed_by_user_id IS NULL AND removal_reason IS NULL)
        OR (removed_at IS NOT NULL AND removed_by_user_id IS NOT NULL)
    )
);

CREATE TABLE lab_results (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_set_id NUMBER(19) NOT NULL REFERENCES lab_result_sets(id) ON DELETE CASCADE,
    test_definition_id NUMBER(19) NOT NULL REFERENCES lab_test_definitions(id),
    reported_value NUMBER(18, 6) NOT NULL CHECK (reported_value >= 0),
    reported_unit VARCHAR2(40) NOT NULL,
    canonical_value NUMBER(18, 6) NOT NULL CHECK (canonical_value >= 0),
    canonical_unit VARCHAR2(40) NOT NULL,
    reference_lower NUMBER(18, 6) CHECK (reference_lower >= 0),
    reference_upper NUMBER(18, 6) CHECK (reference_upper >= 0),
    UNIQUE (result_set_id, test_definition_id),
    CONSTRAINT chk_lab_result_reference CHECK (
        reference_lower IS NULL OR reference_upper IS NULL OR reference_lower <= reference_upper
    )
);

CREATE TABLE lab_result_audit_events (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    result_set_id NUMBER(19) NOT NULL REFERENCES lab_result_sets(id),
    patient_profile_id NUMBER(19) NOT NULL REFERENCES patient_profiles(id),
    action VARCHAR2(20) NOT NULL,
    actor_user_id NUMBER(19) NOT NULL REFERENCES users(id),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    before_snapshot CLOB,
    after_snapshot CLOB
);

CREATE OR REPLACE TRIGGER chk_lab_audit_snapshots
    BEFORE INSERT OR UPDATE OF action, before_snapshot, after_snapshot ON lab_result_audit_events
    FOR EACH ROW
BEGIN
    IF :NEW.action = 'CREATE' THEN
        IF :NEW.before_snapshot IS NOT NULL OR :NEW.after_snapshot IS NULL THEN
            RAISE_APPLICATION_ERROR(-20007, 'Invalid CREATE lab audit snapshots');
        END IF;
    ELSIF :NEW.action IN ('UPDATE', 'REMOVE') THEN
        IF :NEW.before_snapshot IS NULL OR :NEW.after_snapshot IS NULL THEN
            RAISE_APPLICATION_ERROR(-20007, 'Invalid UPDATE or REMOVE lab audit snapshots');
        END IF;
    ELSE
        RAISE_APPLICATION_ERROR(-20007, 'Invalid lab audit action');
    END IF;
END;
/

CREATE INDEX idx_lab_result_sets_patient_date
    ON lab_result_sets (
        CASE WHEN removed_at IS NULL THEN patient_profile_id END,
        CASE WHEN removed_at IS NULL THEN collection_date END DESC
    );
CREATE INDEX idx_lab_results_definition ON lab_results(test_definition_id, result_set_id);
CREATE INDEX idx_lab_audit_set_time ON lab_result_audit_events(result_set_id, occurred_at);

INSERT INTO lab_test_definitions
    (code, label_key, category, canonical_unit, display_scale, active, sort_order)
SELECT 'CRP', 'lab.test.crp', 'INFLAMMATION', 'mg/L', 2, TRUE, 10 FROM dual
UNION ALL SELECT 'FECAL_CALPROTECTIN', 'lab.test.fecalCalprotectin', 'INFLAMMATION', 'ug/g', 0, TRUE, 20 FROM dual
UNION ALL SELECT 'HEMOGLOBIN', 'lab.test.hemoglobin', 'HEMATOLOGY', 'g/L', 1, TRUE, 30 FROM dual
UNION ALL SELECT 'FERRITIN', 'lab.test.ferritin', 'HEMATOLOGY', 'ug/L', 1, TRUE, 40 FROM dual
UNION ALL SELECT 'VITAMIN_D_25_OH', 'lab.test.vitaminD25Oh', 'NUTRITION', 'ng/mL', 1, TRUE, 50 FROM dual
UNION ALL SELECT 'VITAMIN_B12', 'lab.test.vitaminB12', 'NUTRITION', 'pg/mL', 0, TRUE, 60 FROM dual
UNION ALL SELECT 'ALBUMIN', 'lab.test.albumin', 'NUTRITION', 'g/L', 1, TRUE, 70 FROM dual
UNION ALL SELECT 'SODIUM', 'lab.test.sodium', 'ELECTROLYTE', 'mmol/L', 1, TRUE, 80 FROM dual
UNION ALL SELECT 'POTASSIUM', 'lab.test.potassium', 'ELECTROLYTE', 'mmol/L', 2, TRUE, 90 FROM dual
UNION ALL SELECT 'CHLORIDE', 'lab.test.chloride', 'ELECTROLYTE', 'mmol/L', 1, TRUE, 100 FROM dual
UNION ALL SELECT 'MAGNESIUM', 'lab.test.magnesium', 'ELECTROLYTE', 'mmol/L', 2, TRUE, 110 FROM dual
UNION ALL SELECT 'CALCIUM', 'lab.test.calcium', 'ELECTROLYTE', 'mmol/L', 2, TRUE, 120 FROM dual
UNION ALL SELECT 'ALT', 'lab.test.alt', 'LIVER', 'U/L', 0, TRUE, 130 FROM dual
UNION ALL SELECT 'AST', 'lab.test.ast', 'LIVER', 'U/L', 0, TRUE, 140 FROM dual
UNION ALL SELECT 'ALP', 'lab.test.alp', 'LIVER', 'U/L', 0, TRUE, 150 FROM dual
UNION ALL SELECT 'GGT', 'lab.test.ggt', 'LIVER', 'U/L', 0, TRUE, 160 FROM dual
UNION ALL SELECT 'BILIRUBIN_TOTAL', 'lab.test.bilirubinTotal', 'LIVER', 'umol/L', 1, TRUE, 170 FROM dual
UNION ALL SELECT 'CREATININE', 'lab.test.creatinine', 'KIDNEY', 'umol/L', 1, TRUE, 180 FROM dual
UNION ALL SELECT 'EGFR', 'lab.test.egfr', 'KIDNEY', 'mL/min/1.73m2', 0, TRUE, 190 FROM dual
UNION ALL SELECT 'UREA', 'lab.test.urea', 'KIDNEY', 'mmol/L', 2, TRUE, 200 FROM dual;

INSERT INTO lab_test_unit_definitions
    (test_definition_id, unit_code, conversion_type, multiplier, sort_order)
SELECT id, canonical_unit, 'IDENTITY', 1, 0
FROM lab_test_definitions;

INSERT INTO lab_test_unit_definitions
    (test_definition_id, unit_code, conversion_type, multiplier, sort_order)
SELECT id, 'mg/dL', 'MULTIPLY', 10, 1 FROM lab_test_definitions WHERE code = 'CRP'
UNION ALL
SELECT id, 'g/dL', 'MULTIPLY', 10, 1 FROM lab_test_definitions WHERE code = 'HEMOGLOBIN'
UNION ALL
SELECT id, 'ng/mL', 'IDENTITY', 1, 1 FROM lab_test_definitions WHERE code = 'FERRITIN'
UNION ALL
SELECT id, 'ug/L', 'IDENTITY', 1, 1 FROM lab_test_definitions WHERE code = 'VITAMIN_D_25_OH'
UNION ALL
SELECT id, 'ng/L', 'IDENTITY', 1, 1 FROM lab_test_definitions WHERE code = 'VITAMIN_B12'
UNION ALL
SELECT id, 'g/dL', 'MULTIPLY', 10, 1 FROM lab_test_definitions WHERE code = 'ALBUMIN';
