CREATE TABLE users (
    id                     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                  VARCHAR2(255) NOT NULL UNIQUE,
    password_hash          VARCHAR2(255) NOT NULL,
    enabled                BOOLEAN DEFAULT FALSE NOT NULL,
    failed_login_attempts  NUMBER(10) DEFAULT 0 NOT NULL,
    locked_until           TIMESTAMP WITH TIME ZONE,
    mfa_enabled            BOOLEAN DEFAULT FALSE NOT NULL,
    mfa_secret_encrypted   BLOB,
    created_at             TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at             TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE user_roles (
    user_id  NUMBER(19) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role     VARCHAR2(50) NOT NULL,
    PRIMARY KEY (user_id, role)
);
