CREATE TABLE red_flag_rules (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stable_key VARCHAR2(120) NOT NULL UNIQUE,
    display_name VARCHAR2(200) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE red_flag_rule_versions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id NUMBER(19) NOT NULL REFERENCES red_flag_rules(id),
    version_number NUMBER(10) NOT NULL CHECK (version_number > 0),
    status VARCHAR2(20) NOT NULL CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    trigger_source VARCHAR2(32) NOT NULL
        CHECK (trigger_source IN ('SYMPTOM_CHECK_IN', 'LAB_RESULT_SET')),
    severity VARCHAR2(24) NOT NULL
        CHECK (severity IN ('ROUTINE_REVIEW', 'URGENT_REVIEW', 'EMERGENCY')),
    evidence_reference VARCHAR2(1000) NOT NULL,
    rationale VARCHAR2(2000) NOT NULL,
    author_reference VARCHAR2(200) NOT NULL,
    change_summary VARCHAR2(1000) NOT NULL,
    approval_reference VARCHAR2(500),
    approved_at TIMESTAMP WITH TIME ZONE,
    activated_at TIMESTAMP WITH TIME ZONE,
    retired_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    UNIQUE (rule_id, version_number),
    CONSTRAINT chk_red_flag_active_approval CHECK (
        status <> 'ACTIVE'
        OR (approval_reference IS NOT NULL AND approved_at IS NOT NULL AND activated_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX uq_red_flag_rule_one_active_version
    ON red_flag_rule_versions (
        CASE WHEN status = 'ACTIVE' THEN rule_id END
    );

CREATE TABLE red_flag_rule_condition_groups (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_version_id NUMBER(19) NOT NULL REFERENCES red_flag_rule_versions(id),
    stable_key VARCHAR2(120) NOT NULL,
    sort_order NUMBER(10) NOT NULL CHECK (sort_order > 0),
    UNIQUE (rule_version_id, stable_key),
    UNIQUE (rule_version_id, sort_order),
    UNIQUE (id, rule_version_id)
);

CREATE TABLE red_flag_rule_conditions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condition_group_id NUMBER(19) NOT NULL REFERENCES red_flag_rule_condition_groups(id),
    source_type VARCHAR2(32) NOT NULL
        CHECK (source_type IN ('SYMPTOM_CHECK_IN', 'LAB_RESULT_SET', 'PATIENT_PROFILE')),
    fact_key VARCHAR2(160) NOT NULL,
    comparison_operator VARCHAR2(8) NOT NULL
        CHECK (comparison_operator IN ('EQ', 'GT', 'GTE', 'LT', 'LTE')),
    decimal_operand NUMBER(18, 6),
    text_operand VARCHAR2(160),
    lookback_days NUMBER(10) DEFAULT 0 NOT NULL CHECK (lookback_days >= 0),
    sort_order NUMBER(10) NOT NULL CHECK (sort_order > 0),
    UNIQUE (condition_group_id, sort_order),
    CONSTRAINT chk_red_flag_condition_one_operand CHECK (
        (decimal_operand IS NOT NULL AND text_operand IS NULL)
        OR (decimal_operand IS NULL AND text_operand IS NOT NULL)
    )
);

CREATE TABLE red_flag_rule_transitions (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_version_id NUMBER(19) NOT NULL REFERENCES red_flag_rule_versions(id),
    previous_status VARCHAR2(20) CHECK (previous_status IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    new_status VARCHAR2(20) NOT NULL CHECK (new_status IN ('DRAFT', 'ACTIVE', 'RETIRED')),
    actor_reference VARCHAR2(200) NOT NULL,
    transitioned_at TIMESTAMP WITH TIME ZONE NOT NULL,
    change_note VARCHAR2(1000) NOT NULL,
    CONSTRAINT chk_red_flag_rule_transition_forward_only CHECK (
        (previous_status IS NULL AND new_status = 'DRAFT')
        OR (previous_status = 'DRAFT' AND new_status = 'ACTIVE')
        OR (previous_status = 'ACTIVE' AND new_status = 'RETIRED')
    )
);

CREATE INDEX idx_red_flag_rule_transitions_version_time
    ON red_flag_rule_transitions(rule_version_id, transitioned_at, id);

CREATE TABLE red_flag_evaluation_runs (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_profile_id NUMBER(19) NOT NULL REFERENCES patient_profiles(id),
    source_type VARCHAR2(32) NOT NULL
        CHECK (source_type IN ('SYMPTOM_CHECK_IN', 'LAB_RESULT_SET')),
    source_id NUMBER(19) NOT NULL,
    source_operation VARCHAR2(16) NOT NULL CHECK (source_operation IN ('UPSERT', 'REMOVE')),
    evaluated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    overall_severity VARCHAR2(24)
        CHECK (overall_severity IN ('ROUTINE_REVIEW', 'URGENT_REVIEW', 'EMERGENCY')),
    is_current BOOLEAN DEFAULT FALSE NOT NULL,
    superseded_by_run_id NUMBER(19) REFERENCES red_flag_evaluation_runs(id),
    CONSTRAINT chk_red_flag_run_supersession CHECK (
        superseded_by_run_id IS NULL OR is_current = FALSE
    )
);

CREATE UNIQUE INDEX uq_red_flag_evaluation_current_source
    ON red_flag_evaluation_runs (
        CASE WHEN is_current = TRUE THEN source_type END,
        CASE WHEN is_current = TRUE THEN source_id END
    );
CREATE INDEX idx_red_flag_evaluation_patient_time
    ON red_flag_evaluation_runs(patient_profile_id, evaluated_at DESC, id DESC);

CREATE TABLE red_flag_trigger_events (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_run_id NUMBER(19) NOT NULL REFERENCES red_flag_evaluation_runs(id),
    rule_version_id NUMBER(19) NOT NULL REFERENCES red_flag_rule_versions(id),
    matched_group_id NUMBER(19) NOT NULL,
    severity VARCHAR2(24) NOT NULL
        CHECK (severity IN ('ROUTINE_REVIEW', 'URGENT_REVIEW', 'EMERGENCY')),
    triggered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    matched_inputs CLOB NOT NULL,
    UNIQUE (evaluation_run_id, rule_version_id),
    FOREIGN KEY (matched_group_id, rule_version_id)
        REFERENCES red_flag_rule_condition_groups(id, rule_version_id)
);

CREATE INDEX idx_red_flag_trigger_events_run_time
    ON red_flag_trigger_events(evaluation_run_id, triggered_at, id);

INSERT INTO red_flag_rules (stable_key, display_name, created_at)
SELECT 'SYM_SEVERE_ABDOMINAL_PAIN', 'Severe abdominal pain',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'SYM_SIGNIFICANT_BLEEDING', 'Significant bleeding',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'SYM_ACTIVE_FLARE', 'Active flare',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'SYM_HIGH_STOOL_FREQUENCY', 'High stool frequency',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'SYM_COMBINED_SEVERE_ACTIVITY', 'Combined severe symptom activity',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'SYM_SUSPECTED_FLARE', 'Suspected flare',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'SYM_MODERATE_DETERIORATION', 'Moderate symptom deterioration',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'LAB_SODIUM_CRITICAL', 'Critical sodium',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'LAB_POTASSIUM_CRITICAL', 'Critical potassium',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'LAB_CRP_CRITICAL', 'Critical CRP',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'LAB_CRP_HIGH', 'High CRP',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'Elevated CRP with symptom context',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'LAB_HEMOGLOBIN_CRITICAL_LOW', 'Critically low haemoglobin',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'LAB_MAGNESIUM_CRITICAL_LOW', 'Critically low magnesium',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'LAB_UREA_CRITICAL_HIGH', 'Critically high urea',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'LAB_CREATININE_CRITICAL_HIGH', 'Critically high creatinine',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'LAB_TRANSAMINASE_CRITICAL_HIGH', 'Critically high transaminase',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'LAB_ALBUMIN_CRITICAL_LOW', 'Critically low albumin',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'LAB_CALPROTECTIN_HIGH', 'High faecal calprotectin',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'LAB_CRP_ELEVATED', 'Elevated CRP',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'LAB_ALBUMIN_LOW', 'Low albumin',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'LAB_HEMOGLOBIN_LOW_MALE', 'Low haemoglobin for male profile',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'LAB_HEMOGLOBIN_LOW_FEMALE', 'Low haemoglobin for female profile',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual
UNION ALL SELECT 'LAB_CALPROTECTIN_BORDERLINE', 'Borderline faecal calprotectin',
       TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') FROM dual;

INSERT INTO red_flag_rule_versions (
    rule_id, version_number, status, trigger_source, severity,
    evidence_reference, rationale, author_reference, change_summary,
    approval_reference, approved_at, activated_at, retired_at, created_at)
SELECT
    rule_row.id,
    1,
    'ACTIVE',
    CASE WHEN rule_row.stable_key LIKE 'SYM_%' THEN 'SYMPTOM_CHECK_IN' ELSE 'LAB_RESULT_SET' END,
    CASE
        WHEN rule_row.stable_key IN (
            'SYM_SEVERE_ABDOMINAL_PAIN', 'SYM_SIGNIFICANT_BLEEDING',
            'LAB_SODIUM_CRITICAL', 'LAB_POTASSIUM_CRITICAL', 'LAB_CRP_CRITICAL') THEN 'EMERGENCY'
        WHEN rule_row.stable_key IN (
            'SYM_ACTIVE_FLARE', 'SYM_HIGH_STOOL_FREQUENCY', 'SYM_COMBINED_SEVERE_ACTIVITY',
            'LAB_CRP_HIGH', 'LAB_CRP_SYMPTOM_CONTEXT', 'LAB_HEMOGLOBIN_CRITICAL_LOW',
            'LAB_MAGNESIUM_CRITICAL_LOW', 'LAB_UREA_CRITICAL_HIGH',
            'LAB_CREATININE_CRITICAL_HIGH', 'LAB_TRANSAMINASE_CRITICAL_HIGH',
            'LAB_ALBUMIN_CRITICAL_LOW', 'LAB_CALPROTECTIN_HIGH') THEN 'URGENT_REVIEW'
        ELSE 'ROUTINE_REVIEW'
    END,
    CASE
        WHEN rule_row.stable_key IN ('SYM_SEVERE_ABDOMINAL_PAIN', 'SYM_SIGNIFICANT_BLEEDING')
            THEN 'https://www.nhs.uk/conditions/inflammatory-bowel-disease/'
        WHEN rule_row.stable_key LIKE 'SYM_%'
            THEN 'https://www.nice.org.uk/guidance/ng130/chapter/recommendations'
        WHEN rule_row.stable_key LIKE 'LAB_CALPROTECTIN_%'
            THEN 'https://www.ouh.nhs.uk/biochemistry/tests/tests-catalogue/calprotectin-faecal/'
        WHEN rule_row.stable_key LIKE 'LAB_HEMOGLOBIN_%'
            THEN 'https://www.gloshospitals.nhs.uk/our-services/services-we-offer/pathology/haematology/haematology-reference-ranges/'
        WHEN rule_row.stable_key IN ('LAB_CRP_HIGH', 'LAB_CRP_ELEVATED', 'LAB_CRP_SYMPTOM_CONTEXT')
            THEN 'https://www.nice.org.uk/advice/mib81/chapter/the-technology'
        WHEN rule_row.stable_key = 'LAB_CRP_CRITICAL'
            THEN 'https://sheffieldlaboratorymedicine.nhs.uk/search-test.php?search=3079'
        ELSE 'https://mft.nhs.uk/the-trust/other-departments/laboratory-medicine/information-for-gps/laboratory-medicines-newsletter-for-gps/the-communication-of-critical-biochemistry-results/'
    END,
    'Initial approved MET-12 threshold for ' || rule_row.display_name || '.',
    'MET-12',
    'Add the initial clinically approved red-flag rule version.',
    'MET-12 initial clinical baseline approved 2026-07-29',
    TO_TIMESTAMP_TZ('2026-07-29 10:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
    TO_TIMESTAMP_TZ('2026-07-29 10:05:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
    NULL,
    TO_TIMESTAMP_TZ('2026-07-29 09:00:00 +00:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM')
FROM red_flag_rules rule_row;

INSERT INTO red_flag_rule_condition_groups (rule_version_id, stable_key, sort_order)
SELECT rule_version.id, group_seed.stable_key, group_seed.sort_order
FROM (
    SELECT 'SYM_SEVERE_ABDOMINAL_PAIN' rule_key, 'G1' stable_key, 1 sort_order FROM dual
    UNION ALL SELECT 'SYM_SIGNIFICANT_BLEEDING', 'G1', 1 FROM dual
    UNION ALL SELECT 'SYM_ACTIVE_FLARE', 'G1', 1 FROM dual
    UNION ALL SELECT 'SYM_HIGH_STOOL_FREQUENCY', 'G1', 1 FROM dual
    UNION ALL SELECT 'SYM_COMBINED_SEVERE_ACTIVITY', 'G1', 1 FROM dual
    UNION ALL SELECT 'SYM_COMBINED_SEVERE_ACTIVITY', 'G2', 2 FROM dual
    UNION ALL SELECT 'SYM_COMBINED_SEVERE_ACTIVITY', 'G3', 3 FROM dual
    UNION ALL SELECT 'SYM_SUSPECTED_FLARE', 'G1', 1 FROM dual
    UNION ALL SELECT 'SYM_MODERATE_DETERIORATION', 'G1', 1 FROM dual
    UNION ALL SELECT 'SYM_MODERATE_DETERIORATION', 'G2', 2 FROM dual
    UNION ALL SELECT 'SYM_MODERATE_DETERIORATION', 'G3', 3 FROM dual
    UNION ALL SELECT 'SYM_MODERATE_DETERIORATION', 'G4', 4 FROM dual
    UNION ALL SELECT 'LAB_SODIUM_CRITICAL', 'G1', 1 FROM dual
    UNION ALL SELECT 'LAB_SODIUM_CRITICAL', 'G2', 2 FROM dual
    UNION ALL SELECT 'LAB_POTASSIUM_CRITICAL', 'G1', 1 FROM dual
    UNION ALL SELECT 'LAB_POTASSIUM_CRITICAL', 'G2', 2 FROM dual
    UNION ALL SELECT 'LAB_CRP_CRITICAL', 'G1', 1 FROM dual
    UNION ALL SELECT 'LAB_CRP_HIGH', 'G1', 1 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G1', 1 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G2', 2 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G3', 3 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G4', 4 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G5', 5 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G6', 6 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G7', 7 FROM dual
    UNION ALL SELECT 'LAB_HEMOGLOBIN_CRITICAL_LOW', 'G1', 1 FROM dual
    UNION ALL SELECT 'LAB_MAGNESIUM_CRITICAL_LOW', 'G1', 1 FROM dual
    UNION ALL SELECT 'LAB_UREA_CRITICAL_HIGH', 'G1', 1 FROM dual
    UNION ALL SELECT 'LAB_CREATININE_CRITICAL_HIGH', 'G1', 1 FROM dual
    UNION ALL SELECT 'LAB_TRANSAMINASE_CRITICAL_HIGH', 'G1', 1 FROM dual
    UNION ALL SELECT 'LAB_TRANSAMINASE_CRITICAL_HIGH', 'G2', 2 FROM dual
    UNION ALL SELECT 'LAB_ALBUMIN_CRITICAL_LOW', 'G1', 1 FROM dual
    UNION ALL SELECT 'LAB_CALPROTECTIN_HIGH', 'G1', 1 FROM dual
    UNION ALL SELECT 'LAB_CRP_ELEVATED', 'G1', 1 FROM dual
    UNION ALL SELECT 'LAB_ALBUMIN_LOW', 'G1', 1 FROM dual
    UNION ALL SELECT 'LAB_HEMOGLOBIN_LOW_MALE', 'G1', 1 FROM dual
    UNION ALL SELECT 'LAB_HEMOGLOBIN_LOW_FEMALE', 'G1', 1 FROM dual
    UNION ALL SELECT 'LAB_CALPROTECTIN_BORDERLINE', 'G1', 1 FROM dual
) group_seed
JOIN red_flag_rules rule_row ON rule_row.stable_key = group_seed.rule_key
JOIN red_flag_rule_versions rule_version
    ON rule_version.rule_id = rule_row.id AND rule_version.version_number = 1;

INSERT INTO red_flag_rule_conditions (
    condition_group_id, source_type, fact_key, comparison_operator,
    decimal_operand, text_operand, lookback_days, sort_order)
SELECT
    condition_group.id,
    condition_seed.source_type,
    condition_seed.fact_key,
    condition_seed.comparison_operator,
    condition_seed.decimal_operand,
    condition_seed.text_operand,
    condition_seed.lookback_days,
    condition_seed.sort_order
FROM (
    SELECT 'SYM_SEVERE_ABDOMINAL_PAIN' rule_key, 'G1' group_key,
           'SYMPTOM_CHECK_IN' source_type, 'symptom.abdominal_pain' fact_key,
           'EQ' comparison_operator, CAST(NULL AS NUMBER(18,6)) decimal_operand,
           CAST('severe' AS VARCHAR2(160)) text_operand, 0 lookback_days, 1 sort_order FROM dual
    UNION ALL SELECT 'SYM_SIGNIFICANT_BLEEDING', 'G1', 'SYMPTOM_CHECK_IN', 'symptom.blood_in_stool', 'EQ', NULL, 'significant', 0, 1 FROM dual
    UNION ALL SELECT 'SYM_ACTIVE_FLARE', 'G1', 'SYMPTOM_CHECK_IN', 'symptom.flare_state', 'EQ', NULL, 'ACTIVE_FLARE', 0, 1 FROM dual
    UNION ALL SELECT 'SYM_HIGH_STOOL_FREQUENCY', 'G1', 'SYMPTOM_CHECK_IN', 'symptom.stool_frequency', 'GT', 8, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'SYM_COMBINED_SEVERE_ACTIVITY', 'G1', 'SYMPTOM_CHECK_IN', 'symptom.stool_frequency', 'GTE', 6, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'SYM_COMBINED_SEVERE_ACTIVITY', 'G1', 'SYMPTOM_CHECK_IN', 'symptom.blood_in_stool', 'EQ', NULL, 'visible', 0, 2 FROM dual
    UNION ALL SELECT 'SYM_COMBINED_SEVERE_ACTIVITY', 'G2', 'SYMPTOM_CHECK_IN', 'symptom.stool_frequency', 'GTE', 6, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'SYM_COMBINED_SEVERE_ACTIVITY', 'G2', 'SYMPTOM_CHECK_IN', 'symptom.abdominal_pain', 'EQ', NULL, 'moderate', 0, 2 FROM dual
    UNION ALL SELECT 'SYM_COMBINED_SEVERE_ACTIVITY', 'G3', 'SYMPTOM_CHECK_IN', 'symptom.stool_frequency', 'GTE', 6, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'SYM_COMBINED_SEVERE_ACTIVITY', 'G3', 'SYMPTOM_CHECK_IN', 'symptom.general_wellbeing', 'EQ', NULL, 'very-unwell', 0, 2 FROM dual
    UNION ALL SELECT 'SYM_SUSPECTED_FLARE', 'G1', 'SYMPTOM_CHECK_IN', 'symptom.flare_state', 'EQ', NULL, 'SUSPECTED_FLARE', 0, 1 FROM dual
    UNION ALL SELECT 'SYM_MODERATE_DETERIORATION', 'G1', 'SYMPTOM_CHECK_IN', 'symptom.stool_frequency', 'GTE', 4, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'SYM_MODERATE_DETERIORATION', 'G1', 'SYMPTOM_CHECK_IN', 'symptom.stool_frequency', 'LTE', 5, NULL, 0, 2 FROM dual
    UNION ALL SELECT 'SYM_MODERATE_DETERIORATION', 'G2', 'SYMPTOM_CHECK_IN', 'symptom.blood_in_stool', 'EQ', NULL, 'visible', 0, 1 FROM dual
    UNION ALL SELECT 'SYM_MODERATE_DETERIORATION', 'G3', 'SYMPTOM_CHECK_IN', 'symptom.abdominal_pain', 'EQ', NULL, 'moderate', 0, 1 FROM dual
    UNION ALL SELECT 'SYM_MODERATE_DETERIORATION', 'G4', 'SYMPTOM_CHECK_IN', 'symptom.general_wellbeing', 'EQ', NULL, 'very-unwell', 0, 1 FROM dual
    UNION ALL SELECT 'LAB_SODIUM_CRITICAL', 'G1', 'LAB_RESULT_SET', 'lab.SODIUM', 'LTE', 120, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_SODIUM_CRITICAL', 'G2', 'LAB_RESULT_SET', 'lab.SODIUM', 'GTE', 160, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_POTASSIUM_CRITICAL', 'G1', 'LAB_RESULT_SET', 'lab.POTASSIUM', 'LTE', 2.5, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_POTASSIUM_CRITICAL', 'G2', 'LAB_RESULT_SET', 'lab.POTASSIUM', 'GTE', 6.5, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_CRP_CRITICAL', 'G1', 'LAB_RESULT_SET', 'lab.CRP', 'GTE', 300, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_CRP_HIGH', 'G1', 'LAB_RESULT_SET', 'lab.CRP', 'GTE', 100, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_CRP_HIGH', 'G1', 'LAB_RESULT_SET', 'lab.CRP', 'LT', 300, NULL, 0, 2 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G1', 'LAB_RESULT_SET', 'lab.CRP', 'GT', 45, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G1', 'LAB_RESULT_SET', 'lab.CRP', 'LT', 100, NULL, 0, 2 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G1', 'SYMPTOM_CHECK_IN', 'symptom.flare_state', 'EQ', NULL, 'ACTIVE_FLARE', 7, 3 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G2', 'LAB_RESULT_SET', 'lab.CRP', 'GT', 45, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G2', 'LAB_RESULT_SET', 'lab.CRP', 'LT', 100, NULL, 0, 2 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G2', 'SYMPTOM_CHECK_IN', 'symptom.stool_frequency', 'GT', 8, NULL, 7, 3 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G3', 'LAB_RESULT_SET', 'lab.CRP', 'GT', 45, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G3', 'LAB_RESULT_SET', 'lab.CRP', 'LT', 100, NULL, 0, 2 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G3', 'SYMPTOM_CHECK_IN', 'symptom.stool_frequency', 'GTE', 6, NULL, 7, 3 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G3', 'SYMPTOM_CHECK_IN', 'symptom.blood_in_stool', 'EQ', NULL, 'visible', 7, 4 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G4', 'LAB_RESULT_SET', 'lab.CRP', 'GT', 45, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G4', 'LAB_RESULT_SET', 'lab.CRP', 'LT', 100, NULL, 0, 2 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G4', 'SYMPTOM_CHECK_IN', 'symptom.stool_frequency', 'GTE', 6, NULL, 7, 3 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G4', 'SYMPTOM_CHECK_IN', 'symptom.abdominal_pain', 'EQ', NULL, 'moderate', 7, 4 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G5', 'LAB_RESULT_SET', 'lab.CRP', 'GT', 45, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G5', 'LAB_RESULT_SET', 'lab.CRP', 'LT', 100, NULL, 0, 2 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G5', 'SYMPTOM_CHECK_IN', 'symptom.stool_frequency', 'GTE', 6, NULL, 7, 3 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G5', 'SYMPTOM_CHECK_IN', 'symptom.general_wellbeing', 'EQ', NULL, 'very-unwell', 7, 4 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G6', 'LAB_RESULT_SET', 'lab.CRP', 'GT', 45, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G6', 'LAB_RESULT_SET', 'lab.CRP', 'LT', 100, NULL, 0, 2 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G6', 'SYMPTOM_CHECK_IN', 'symptom.abdominal_pain', 'EQ', NULL, 'severe', 7, 3 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G7', 'LAB_RESULT_SET', 'lab.CRP', 'GT', 45, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G7', 'LAB_RESULT_SET', 'lab.CRP', 'LT', 100, NULL, 0, 2 FROM dual
    UNION ALL SELECT 'LAB_CRP_SYMPTOM_CONTEXT', 'G7', 'SYMPTOM_CHECK_IN', 'symptom.blood_in_stool', 'EQ', NULL, 'significant', 7, 3 FROM dual
    UNION ALL SELECT 'LAB_HEMOGLOBIN_CRITICAL_LOW', 'G1', 'LAB_RESULT_SET', 'lab.HEMOGLOBIN', 'LTE', 70, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_MAGNESIUM_CRITICAL_LOW', 'G1', 'LAB_RESULT_SET', 'lab.MAGNESIUM', 'LTE', 0.40, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_UREA_CRITICAL_HIGH', 'G1', 'LAB_RESULT_SET', 'lab.UREA', 'GTE', 30, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_CREATININE_CRITICAL_HIGH', 'G1', 'LAB_RESULT_SET', 'lab.CREATININE', 'GTE', 354, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_TRANSAMINASE_CRITICAL_HIGH', 'G1', 'LAB_RESULT_SET', 'lab.ALT', 'GTE', 500, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_TRANSAMINASE_CRITICAL_HIGH', 'G2', 'LAB_RESULT_SET', 'lab.AST', 'GTE', 500, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_ALBUMIN_CRITICAL_LOW', 'G1', 'LAB_RESULT_SET', 'lab.ALBUMIN', 'LTE', 10, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_CALPROTECTIN_HIGH', 'G1', 'LAB_RESULT_SET', 'lab.FECAL_CALPROTECTIN', 'GT', 250, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_CRP_ELEVATED', 'G1', 'LAB_RESULT_SET', 'lab.CRP', 'GT', 45, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_CRP_ELEVATED', 'G1', 'LAB_RESULT_SET', 'lab.CRP', 'LT', 100, NULL, 0, 2 FROM dual
    UNION ALL SELECT 'LAB_ALBUMIN_LOW', 'G1', 'LAB_RESULT_SET', 'lab.ALBUMIN', 'GT', 10, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_ALBUMIN_LOW', 'G1', 'LAB_RESULT_SET', 'lab.ALBUMIN', 'LT', 30, NULL, 0, 2 FROM dual
    UNION ALL SELECT 'LAB_HEMOGLOBIN_LOW_MALE', 'G1', 'LAB_RESULT_SET', 'lab.HEMOGLOBIN', 'GT', 70, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_HEMOGLOBIN_LOW_MALE', 'G1', 'LAB_RESULT_SET', 'lab.HEMOGLOBIN', 'LTE', 130, NULL, 0, 2 FROM dual
    UNION ALL SELECT 'LAB_HEMOGLOBIN_LOW_MALE', 'G1', 'PATIENT_PROFILE', 'patient.sex', 'EQ', NULL, 'MALE', 0, 3 FROM dual
    UNION ALL SELECT 'LAB_HEMOGLOBIN_LOW_FEMALE', 'G1', 'LAB_RESULT_SET', 'lab.HEMOGLOBIN', 'GT', 70, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_HEMOGLOBIN_LOW_FEMALE', 'G1', 'LAB_RESULT_SET', 'lab.HEMOGLOBIN', 'LTE', 120, NULL, 0, 2 FROM dual
    UNION ALL SELECT 'LAB_HEMOGLOBIN_LOW_FEMALE', 'G1', 'PATIENT_PROFILE', 'patient.sex', 'EQ', NULL, 'FEMALE', 0, 3 FROM dual
    UNION ALL SELECT 'LAB_CALPROTECTIN_BORDERLINE', 'G1', 'LAB_RESULT_SET', 'lab.FECAL_CALPROTECTIN', 'GTE', 100, NULL, 0, 1 FROM dual
    UNION ALL SELECT 'LAB_CALPROTECTIN_BORDERLINE', 'G1', 'LAB_RESULT_SET', 'lab.FECAL_CALPROTECTIN', 'LTE', 250, NULL, 0, 2 FROM dual
) condition_seed
JOIN red_flag_rules rule_row ON rule_row.stable_key = condition_seed.rule_key
JOIN red_flag_rule_versions rule_version
    ON rule_version.rule_id = rule_row.id AND rule_version.version_number = 1
JOIN red_flag_rule_condition_groups condition_group
    ON condition_group.rule_version_id = rule_version.id
    AND condition_group.stable_key = condition_seed.group_key;

INSERT INTO red_flag_rule_transitions (
    rule_version_id, previous_status, new_status, actor_reference, transitioned_at, change_note)
SELECT id, NULL, 'DRAFT', 'MET-12', created_at, 'Initial rule version drafted.'
FROM red_flag_rule_versions
UNION ALL
SELECT id, 'DRAFT', 'ACTIVE', 'MET-12', activated_at,
       'Initial clinical baseline approved and activated.'
FROM red_flag_rule_versions;

CREATE OR REPLACE TRIGGER red_flag_rule_transitions_append_only
    BEFORE UPDATE OR DELETE ON red_flag_rule_transitions
    FOR EACH ROW
BEGIN
    RAISE_APPLICATION_ERROR(-20008, 'Red-flag rule transitions are append-only');
END;
/
