CREATE TABLE clinical_access_tokens (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL REFERENCES users(id),
    token_hash VARCHAR2(64) NOT NULL UNIQUE,
    client_type VARCHAR2(40) NOT NULL,
    display_label VARCHAR2(120) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    "resource" VARCHAR2(255) NOT NULL,
    last_used_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    revocation_reason VARCHAR2(120),
    refresh_family_id VARCHAR2(64),
    CONSTRAINT fk_clinical_access_tokens_refresh_family
        FOREIGN KEY (refresh_family_id) REFERENCES oauth_refresh_token_families(family_id)
);

CREATE INDEX idx_clinical_access_tokens_user_id
    ON clinical_access_tokens(user_id);

CREATE INDEX idx_clinical_access_tokens_active
    ON clinical_access_tokens(user_id, revoked_at, expires_at);

CREATE INDEX idx_clinical_access_tokens_refresh_family
    ON clinical_access_tokens(refresh_family_id);

CREATE TABLE clinical_access_token_scopes (
    token_id NUMBER(19) NOT NULL REFERENCES clinical_access_tokens(id) ON DELETE CASCADE,
    scope VARCHAR2(80) NOT NULL CHECK (scope LIKE 'clinician:%'),
    PRIMARY KEY (token_id, scope)
);

ALTER TABLE oauth_authorization_codes
    ADD subject_type VARCHAR2(16) DEFAULT 'PATIENT' NOT NULL;

ALTER TABLE oauth_authorization_codes
    ADD CONSTRAINT chk_oauth_authorization_codes_subject_type
        CHECK (subject_type IN ('PATIENT', 'CLINICIAN'));

ALTER TABLE oauth_refresh_tokens
    ADD subject_type VARCHAR2(16) DEFAULT 'PATIENT' NOT NULL;

ALTER TABLE oauth_refresh_tokens
    ADD CONSTRAINT chk_oauth_refresh_tokens_subject_type
        CHECK (subject_type IN ('PATIENT', 'CLINICIAN'));
