CREATE TABLE account_verification_tokens (
    id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER(19) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  VARCHAR2(64) NOT NULL,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_avt_user_id ON account_verification_tokens(user_id);
CREATE UNIQUE INDEX uq_avt_token_hash ON account_verification_tokens(token_hash);

CREATE TABLE password_reset_tokens (
    id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER(19) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  VARCHAR2(64) NOT NULL,
    expires_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    consumed_at TIMESTAMP WITH TIME ZONE,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_prt_user_id ON password_reset_tokens(user_id);
CREATE UNIQUE INDEX uq_prt_token_hash ON password_reset_tokens(token_hash);
