CREATE TABLE roles (
    code            VARCHAR2(50) PRIMARY KEY,
    patient_profile BOOLEAN DEFAULT FALSE NOT NULL,
    clinical_staff  BOOLEAN DEFAULT FALSE NOT NULL
);

INSERT INTO roles (code, patient_profile, clinical_staff)
SELECT 'PATIENT', TRUE, FALSE FROM dual
UNION ALL SELECT 'NUTRITION_SPECIALIST', FALSE, TRUE FROM dual
UNION ALL SELECT 'PHYSICIAN', FALSE, TRUE FROM dual
UNION ALL SELECT 'COORDINATOR', FALSE, TRUE FROM dual
UNION ALL SELECT 'ADMIN', FALSE, FALSE FROM dual;

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_role
    FOREIGN KEY (role) REFERENCES roles(code);

CREATE INDEX idx_user_roles_role ON user_roles(role);

CREATE TABLE patient_profiles (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         NUMBER(19) NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    date_of_birth   DATE,
    sex             VARCHAR2(40),
    country_region  VARCHAR2(100),
    timezone        VARCHAR2(100),
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_patient_profiles_sex
        CHECK (sex IS NULL OR sex IN ('FEMALE', 'MALE', 'INTERSEX', 'PREFER_NOT_TO_SAY'))
);

CREATE TABLE staff_profiles (
    id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER(19) NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE cohorts (
    id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(255) NOT NULL,
    description CLOB,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE patient_cohort_memberships (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_profile_id  NUMBER(19) NOT NULL REFERENCES patient_profiles(id) ON DELETE CASCADE,
    cohort_id           NUMBER(19) NOT NULL REFERENCES cohorts(id) ON DELETE CASCADE,
    assigned_by_user_id NUMBER(19) REFERENCES users(id) ON DELETE SET NULL,
    assigned_at         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ended_at            TIMESTAMP WITH TIME ZONE,
    CONSTRAINT chk_patient_cohort_memberships_interval
        CHECK (ended_at IS NULL OR ended_at >= assigned_at)
);

CREATE UNIQUE INDEX uq_pcm_active_patient_cohort
    ON patient_cohort_memberships (
        CASE WHEN ended_at IS NULL THEN patient_profile_id END,
        CASE WHEN ended_at IS NULL THEN cohort_id END
    );
CREATE INDEX idx_pcm_patient_profile_id ON patient_cohort_memberships(patient_profile_id);
CREATE INDEX idx_pcm_cohort_id ON patient_cohort_memberships(cohort_id);
CREATE INDEX idx_pcm_assigned_by_user_id ON patient_cohort_memberships(assigned_by_user_id);

CREATE TABLE patient_expert_assignments (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_profile_id  NUMBER(19) NOT NULL REFERENCES patient_profiles(id) ON DELETE CASCADE,
    staff_profile_id    NUMBER(19) NOT NULL REFERENCES staff_profiles(id) ON DELETE CASCADE,
    assigned_by_user_id NUMBER(19) REFERENCES users(id) ON DELETE SET NULL,
    assigned_at         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ended_at            TIMESTAMP WITH TIME ZONE,
    CONSTRAINT chk_patient_expert_assignments_interval
        CHECK (ended_at IS NULL OR ended_at >= assigned_at)
);

CREATE UNIQUE INDEX uq_pea_active_patient_staff
    ON patient_expert_assignments (
        CASE WHEN ended_at IS NULL THEN patient_profile_id END,
        CASE WHEN ended_at IS NULL THEN staff_profile_id END
    );
CREATE INDEX idx_pea_patient_profile_id ON patient_expert_assignments(patient_profile_id);
CREATE INDEX idx_pea_staff_profile_id ON patient_expert_assignments(staff_profile_id);
CREATE INDEX idx_pea_assigned_by_user_id ON patient_expert_assignments(assigned_by_user_id);

CREATE TABLE cohort_staff_assignments (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_id           NUMBER(19) NOT NULL REFERENCES cohorts(id) ON DELETE CASCADE,
    staff_profile_id    NUMBER(19) NOT NULL REFERENCES staff_profiles(id) ON DELETE CASCADE,
    assigned_by_user_id NUMBER(19) REFERENCES users(id) ON DELETE SET NULL,
    assigned_at         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ended_at            TIMESTAMP WITH TIME ZONE,
    CONSTRAINT chk_cohort_staff_assignments_interval
        CHECK (ended_at IS NULL OR ended_at >= assigned_at)
);

CREATE UNIQUE INDEX uq_csa_active_cohort_staff
    ON cohort_staff_assignments (
        CASE WHEN ended_at IS NULL THEN cohort_id END,
        CASE WHEN ended_at IS NULL THEN staff_profile_id END
    );
CREATE INDEX idx_csa_cohort_id ON cohort_staff_assignments(cohort_id);
CREATE INDEX idx_csa_staff_profile_id ON cohort_staff_assignments(staff_profile_id);
CREATE INDEX idx_csa_assigned_by_user_id ON cohort_staff_assignments(assigned_by_user_id);

CREATE OR REPLACE TRIGGER trg_staff_profiles_require_clinical_staff_role
    BEFORE INSERT OR UPDATE OF user_id ON staff_profiles
    FOR EACH ROW
DECLARE
    matching_roles NUMBER(10);
BEGIN
    SELECT COUNT(*)
    INTO matching_roles
    FROM user_roles ur
    JOIN roles r ON r.code = ur.role
    WHERE ur.user_id = :NEW.user_id
      AND r.clinical_staff = TRUE;

    IF matching_roles = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Staff profile requires a clinical_staff role');
    END IF;
END;
/

CREATE ASSERTION assert_patient_profile_has_role
CHECK (
    NOT EXISTS (
        SELECT 1
        FROM patient_profiles pp
        WHERE NOT EXISTS (
            SELECT 1
            FROM user_roles ur, roles r
            WHERE r.code = ur.role
              AND ur.user_id = pp.user_id
              AND r.patient_profile = TRUE
        )
    )
)
DEFERRABLE INITIALLY DEFERRED;

CREATE ASSERTION assert_staff_profile_has_role
CHECK (
    NOT EXISTS (
        SELECT 1
        FROM staff_profiles sp
        WHERE NOT EXISTS (
            SELECT 1
            FROM user_roles ur, roles r
            WHERE r.code = ur.role
              AND ur.user_id = sp.user_id
              AND r.clinical_staff = TRUE
        )
    )
)
DEFERRABLE INITIALLY DEFERRED;
