CREATE TABLE staff_invitations (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) NOT NULL,
    token_hash VARCHAR2(64) NOT NULL UNIQUE,
    invited_by_user_id NUMBER(19) REFERENCES users(id) ON DELETE SET NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    accepted_at TIMESTAMP WITH TIME ZONE,
    revoked_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_staff_invitations_token_hash_length CHECK (length(token_hash) = 64),
    CONSTRAINT chk_staff_invitations_email_lower CHECK (email = lower(trim(email)))
);

CREATE TABLE staff_invitation_roles (
    staff_invitation_id NUMBER(19) NOT NULL REFERENCES staff_invitations(id) ON DELETE CASCADE,
    role VARCHAR2(50) NOT NULL REFERENCES roles(code),
    PRIMARY KEY (staff_invitation_id, role)
);

CREATE OR REPLACE TRIGGER trg_staff_invitation_roles_require_clinical_staff_role
    BEFORE INSERT OR UPDATE OF role ON staff_invitation_roles
    FOR EACH ROW
DECLARE
    matching_roles NUMBER(10);
BEGIN
    SELECT COUNT(*)
    INTO matching_roles
    FROM roles
    WHERE code = :NEW.role
      AND clinical_staff = TRUE;

    IF matching_roles = 0 THEN
        RAISE_APPLICATION_ERROR(-20005, 'Staff invitation role must be a clinical_staff role');
    END IF;
END;
/

CREATE UNIQUE INDEX ux_staff_invitations_pending_email
    ON staff_invitations (
        CASE WHEN accepted_at IS NULL AND revoked_at IS NULL THEN email END
    );

CREATE INDEX ix_staff_invitations_email ON staff_invitations(email);
CREATE INDEX ix_staff_invitation_roles_role ON staff_invitation_roles(role);
