ALTER TABLE patient_profiles ADD (
    glucose_unit_preference VARCHAR2(20) DEFAULT 'MMOL_L' NOT NULL,
    CONSTRAINT chk_patient_profiles_glucose_unit_preference
        CHECK (glucose_unit_preference IN ('MMOL_L', 'MG_DL'))
);

CREATE TABLE daily_diet_logs (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_profile_id  NUMBER(19) NOT NULL REFERENCES patient_profiles(id) ON DELETE CASCADE,
    log_date            DATE NOT NULL,
    adherence_level     VARCHAR2(40) NOT NULL,
    appetite_level      VARCHAR2(40) NOT NULL,
    notes               VARCHAR2(1000),
    metadata            VARCHAR2(2000),
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT ux_daily_diet_logs_patient_date
        UNIQUE (patient_profile_id, log_date),
    CONSTRAINT ux_daily_diet_logs_id_patient
        UNIQUE (id, patient_profile_id),
    CONSTRAINT chk_daily_diet_logs_adherence_level
        CHECK (adherence_level IN ('FULL', 'MOSTLY', 'PARTIAL', 'LOW', 'NOT_FOLLOWED')),
    CONSTRAINT chk_daily_diet_logs_appetite_level
        CHECK (appetite_level IN ('LOW', 'NORMAL', 'HIGH', 'VARIABLE')),
    CONSTRAINT chk_daily_diet_logs_notes
        CHECK (notes IS NULL OR length(trim(notes)) > 0),
    CONSTRAINT chk_daily_diet_logs_metadata
        CHECK (metadata IS NULL OR length(trim(metadata)) > 0)
);

CREATE TABLE daily_diet_log_meals (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_diet_log_id   NUMBER(19) NOT NULL REFERENCES daily_diet_logs(id) ON DELETE CASCADE,
    meal_type           VARCHAR2(40) NOT NULL,
    food_category       VARCHAR2(60) NOT NULL,
    food_description    VARCHAR2(500),
    notes               VARCHAR2(1000),
    sort_order          NUMBER(10) DEFAULT 0 NOT NULL,

    CONSTRAINT chk_daily_diet_log_meals_meal_type
        CHECK (meal_type IN ('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', 'DRINK', 'OTHER')),
    CONSTRAINT chk_daily_diet_log_meals_food_category
        CHECK (food_category IN (
            'FATS',
            'PROTEIN',
            'LOW_CARB_VEGETABLES',
            'DAIRY',
            'NUTS_SEEDS',
            'FERMENTED_FOODS',
            'BEVERAGES',
            'SUPPLEMENTS',
            'OTHER'
        )),
    CONSTRAINT ux_daily_diet_log_meals_id_log
        UNIQUE (id, daily_diet_log_id),
    CONSTRAINT chk_daily_diet_log_meals_sort_order
        CHECK (sort_order >= 0)
);

CREATE TABLE daily_diet_log_deviations (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_diet_log_id   NUMBER(19) NOT NULL REFERENCES daily_diet_logs(id) ON DELETE CASCADE,
    deviation_category  VARCHAR2(60) NOT NULL,
    severity            VARCHAR2(40) NOT NULL,
    notes               VARCHAR2(1000),
    sort_order          NUMBER(10) DEFAULT 0 NOT NULL,

    CONSTRAINT chk_daily_diet_log_deviations_category
        CHECK (deviation_category IN (
            'EXCESS_CARBS',
            'NON_PROTOCOL_FOOD',
            'MISSED_MEAL',
            'DINING_OUT',
            'ALCOHOL',
            'GI_TOLERANCE',
            'OTHER'
        )),
    CONSTRAINT chk_daily_diet_log_deviations_severity
        CHECK (severity IN ('MINOR', 'MODERATE', 'MAJOR')),
    CONSTRAINT chk_daily_diet_log_deviations_sort_order
        CHECK (sort_order >= 0)
);

CREATE TABLE daily_diet_log_photo_references (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_diet_log_id   NUMBER(19) NOT NULL,
    meal_id             NUMBER(19) REFERENCES daily_diet_log_meals(id) ON DELETE SET NULL,
    original_filename   VARCHAR2(255),
    content_type        VARCHAR2(120),
    size_bytes          NUMBER(19),
    storage_key         VARCHAR2(500),
    caption             VARCHAR2(500),
    sort_order          NUMBER(10) DEFAULT 0 NOT NULL,

    CONSTRAINT chk_daily_diet_log_photo_references_size
        CHECK (size_bytes IS NULL OR size_bytes >= 0),
    CONSTRAINT fk_daily_diet_log_photo_references_meal_log
        FOREIGN KEY (meal_id, daily_diet_log_id)
        REFERENCES daily_diet_log_meals(id, daily_diet_log_id)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT chk_daily_diet_log_photo_references_sort_order
        CHECK (sort_order >= 0)
);

CREATE TABLE daily_measurement_entries (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_profile_id  NUMBER(19) NOT NULL REFERENCES patient_profiles(id) ON DELETE CASCADE,
    daily_diet_log_id   NUMBER(19) REFERENCES daily_diet_logs(id) ON DELETE SET NULL,
    measurement_type    VARCHAR2(40) NOT NULL,
    value               NUMBER(8,2) NOT NULL,
    unit                VARCHAR2(20) NOT NULL,
    measured_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    context             VARCHAR2(40) NOT NULL,
    notes               VARCHAR2(1000),
    metadata            VARCHAR2(2000),
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT chk_daily_measurement_entries_type
        CHECK (measurement_type IN ('KETONE', 'GLUCOSE')),
    CONSTRAINT chk_daily_measurement_entries_unit
        CHECK (unit IN ('MMOL_L', 'MG_DL')),
    CONSTRAINT chk_daily_measurement_entries_context
        CHECK (context IN ('FASTING', 'PRE_MEAL', 'POST_MEAL', 'BEDTIME', 'SYMPTOMS', 'OTHER')),
    CONSTRAINT chk_daily_measurement_entries_type_unit
        CHECK (
            (measurement_type = 'KETONE' AND unit = 'MMOL_L')
            OR (measurement_type = 'GLUCOSE' AND unit IN ('MMOL_L', 'MG_DL'))
        ),
    CONSTRAINT fk_daily_measurement_entries_log_patient
        FOREIGN KEY (daily_diet_log_id, patient_profile_id)
        REFERENCES daily_diet_logs(id, patient_profile_id)
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT chk_daily_measurement_entries_value_range
        CHECK (
            (measurement_type = 'KETONE' AND unit = 'MMOL_L' AND value BETWEEN 0 AND 15)
            OR (measurement_type = 'GLUCOSE' AND unit = 'MMOL_L' AND value BETWEEN 1 AND 40)
            OR (measurement_type = 'GLUCOSE' AND unit = 'MG_DL' AND value BETWEEN 18 AND 720)
        ),
    CONSTRAINT chk_daily_measurement_entries_metadata
        CHECK (metadata IS NULL OR length(trim(metadata)) > 0)
);

CREATE INDEX ix_daily_diet_logs_patient_date
    ON daily_diet_logs(patient_profile_id, log_date DESC);

CREATE INDEX ix_daily_diet_log_meals_daily_diet_log
    ON daily_diet_log_meals(daily_diet_log_id);

CREATE INDEX ix_daily_diet_log_deviations_daily_diet_log
    ON daily_diet_log_deviations(daily_diet_log_id);

CREATE INDEX ix_daily_diet_log_photo_references_daily_diet_log
    ON daily_diet_log_photo_references(daily_diet_log_id);

CREATE INDEX ix_daily_diet_log_photo_references_meal
    ON daily_diet_log_photo_references(meal_id);

CREATE INDEX ix_daily_measurement_entries_patient_measured_at
    ON daily_measurement_entries(patient_profile_id, measured_at DESC);

CREATE INDEX ix_daily_measurement_entries_daily_diet_log
    ON daily_measurement_entries(daily_diet_log_id);
