# --- App ---
app.base-url=http://localhost:8080

# --- Database (Use H2 for fast dev) ---
#spring.datasource.url=jdbc:h2:mem:metabion;DB_CLOSE_DELAY=-1
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
## --- Flyway ---
#spring.flyway.enabled=true
